package kjd.gspro.api.v1;

import java.io.IOException;
import java.util.concurrent.Flow;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import kjd.gspro.api.Client;
import kjd.gspro.api.ConnectionException;
import kjd.gspro.api.Publisher;
import kjd.gspro.api.Request;
import kjd.gspro.api.Status;
import lombok.Getter;

/**
 * {@link Client} implementation for communication with the GS Pro Open Connect V1 protocol.
 * <p>
 * 
 * @author kenjdavidson
 */
public class ClientImpl implements Client, Flow.Publisher<Status> {
    
    public static final String DEFAULT_HOST = "127.0.0.1";
    public static final Integer DEFAULT_PORT = 921;
    public static final Integer DEFAULT_TIMEOUT = 300;

    private Logger logger = LoggerFactory.getLogger(ClientImpl.class);

    @Getter
    private String host;

    @Getter
    private Integer port;

    @Getter 
    private Integer timeout;

    private Thread connectionThread;

    private ConnectionImpl connection;

    @Getter
    private Publisher<Status> statusPublisher;

    public ClientImpl() {
        this(DEFAULT_HOST, DEFAULT_PORT);
    }

    public ClientImpl(String host) {
        this(host, DEFAULT_PORT);
    }

    public ClientImpl(String host, Integer port) {
        this(host, port, DEFAULT_TIMEOUT);
    }

    public ClientImpl(String host, Integer port, Integer timeout) {
        this.host = host;
        this.port = port;
        this.timeout = timeout;

        this.statusPublisher = new Publisher<>();
    }

    /**
     * Whether we have an active connection to the GS Pro Open Connect V1 server.
     * 
     * @return
     */
    public boolean isConnected() {
        return connection != null && connection.isConnected();
    }

    /**
     * Request a connection to the GS Pro Open Connect V1 server.  The client must be subscribed
     * to in order to get status updates and responses.
     * 
     * @return the {@link ClientImplTest} once the connection is started
     */
    @Override
    public ClientImpl connect() throws ConnectionException {
        if (isConnected()) 
            throw new ConnectionException("Already connected");

        try {
            connection = createConnection();
            connection.connect(host, port);
            connectionThread = new Thread(connection, "gs-pro-api-conn");
            connectionThread.start();
        } catch (ConnectionException e) {
            connection = null;
            connectionThread = null;
            throw e;
        }
        
        return this;
    }

    /**
     * Requests that the client disconnects from the GS Pro Open Connect V1 server.  This may not happen
     * right away; the Subscriptions are still valid and should be monitored for successful disconnect.
     * <p>
     * Look into updating this so that cancel returns a `Future` or `join` with the connection thread
     * to make sure it's completely shut down.
     * 
     * @return the {@link ClientImplTest}
     * @throws InterruptedException
     */
    @Override
    public ClientImpl cancel() throws ConnectionException {
        validateConnection();;

        connection.cancel();
        connection = null;
        connectionThread = null;

        return this;
    }    

    /**
     * Subscription to start receiving Status (and response) messages from the 
     * GS Pro software.
     * 
     * @param subscriber Status subscriber
     */
    @Override
    public void subscribe(Flow.Subscriber<? super Status> subscriber) {
        statusPublisher.subscribe(subscriber);
    }

    /**
     * Send a message to the GS Pro.  Requests should be pre-generated by the monitor
     * adapter/bridge either manually or using the {@link RequestBuilder}.
     * 
     * @param request the {@link Request} to send
     */
    @Override
	public boolean send(Request request) throws ConnectionException {
        validateConnection();

        try {
            connection.write(request);
            return true;
        } catch (IOException e) {
            logger.error("Error sending to GS Pro: {0}", e.getMessage());
            statusPublisher.error(e);
        }

        return false;
	}  

    /**
     * Creates/returns the {@link ConnectionImpl}.
     * 
     * @return the {@link ConnectionImpl} being used.
     */
    protected ConnectionImpl createConnection() {
        return new ConnectionImpl(statusPublisher);
    }

    protected void validateConnection() throws ConnectionException {
        if (connection == null) 
            throw new ConnectionException("Not connected to GS Pro");
    }

}
